---
- hosts: 192.168.0.200
  connection: local
  tasks:
    - name: configure an IPv4 host record
      nios_host_record:
        name: leaf07.ansible.com
        ipv4addrs:
          - ipv4addr:
              "{{ lookup('nios_next_ip', '192.168.200.0/24', provider=nios_provider)[0] }}"
        comment: added from ansible
        state: present
        provider: "{{nios_provider}}"

