---
- hosts: nios
  connection: local
  tasks:
    - name: return the next available network for network 10.10.0.0/16
      set_fact:
        networkaddr: "{{ lookup('nios_next_network', '10.10.0.0/16', cidr=24, num=3, provider=nios_provider) }}"
        provider: "{{ nios_provider }}"
    - name: check the networkviews
      debug:
        var: networkaddr

